[package]
name = "imu_common"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra.workspace = true
uuid.workspace = true

serde = { version = "1", features = ["derive"]}
serde_json = "1"

[dev-dependencies]
once_cell = "1.18"


[features]
default = []
serde-serialize = []