[package]
name = "test_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
num_enum = "0.7"

uuid.workspace = true
nalgebra.workspace = true
dashmap.workspace = true

gnuplot = "0.0.42"

common = {path= "../common"}
publisher = {path = "../publisher"}

