[package]
name = "publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true
env_logger.workspace = true
uuid.workspace = true
dashmap.workspace = true

rayon = "1.10"
common = { path = "../common"}



