name: Rust CI with Coverage

on:
  push:
    branches:
      - main
      - "feature/*"  # Run on feature branches too
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Rust environment
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Step 3: Install cargo-tarpaulin for coverage reporting
      - name: Install cargo-tarpaulin
        run: |
          cargo install cargo-tarpaulin

      # Step 4: Run tests and generate coverage report using cargo-tarpaulin
      - name: Run tests and generate coverage report
        run: |
          cargo tarpaulin --out Xml --skip-clean

      # Step 5: Upload coverage report as artifact
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/debug/deps/coverage.xml  # Location of the coverage report
